services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    env_file:
      - .env.development
  db:
    image: postgres:13
    restart: always
    secrets:
      - POSTGRES_PASSWORD
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: /run/secrets/POSTGRES_PASSWORD
    volumes:
      - postgres-data:/var/lib/postgresql/data

secrets:
  POSTGRES_PASSWORD:
    file: .env.development     
volumes:
  postgres-data: